# Generated by Django 3.1.7 on 2021-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cpassword',
            field=models.TextField(default='abc123'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.TextField(default='abc123'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.TextField(default='123'),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.TextField(default=''),
        ),
    ]
