# Generated by Django 3.1.7 on 2021-03-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20210327_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='email',
        ),
    ]
