# Generated by Django 3.1.7 on 2021-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210327_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
